# Generated by Django 2.2.10 on 2022-01-10 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название опроса')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('finished_at', models.DateTimeField(verbose_name='дата окончания')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='вопрос')),
                ('answer_type', models.CharField(choices=[('TX', 'текст'), ('CH', 'один вариант ответа'), ('MC', 'несколько вариантов ответа')], max_length=2, verbose_name='тип ответа')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Survey', verbose_name='опрос')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='id user')),
                ('answer_text', models.CharField(max_length=256, verbose_name='ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время ответа')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Question', verbose_name='вопрос')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Survey', verbose_name='опрос')),
            ],
        ),
    ]
