# Generated by Django 2.2.10 on 2022-01-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220111_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'ответы', 'verbose_name_plural': 'ответы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата и время ответа'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='finished_at',
            field=models.DateField(verbose_name='дата окончания'),
        ),
    ]
