# Generated by Django 2.2.10 on 2022-01-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220111_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_answer_text', models.CharField(max_length=256, verbose_name='вариант ответа')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Question', verbose_name='вопрос')),
            ],
        ),
    ]
