# Generated by Django 2.2.10 on 2022-01-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20220111_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionanswer',
            name='number_answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
