# Generated by Django 2.2.10 on 2022-01-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_optionanswer_number_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_id', to='main_app.Survey', verbose_name='опрос'),
        ),
    ]
