# Generated by Django 2.2.10 on 2022-01-11 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20220112_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionanswer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='main_app.Question', verbose_name='вопрос'),
        ),
    ]
