# Generated by Django 2.2.10 on 2022-01-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20220112_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='main_app.Question', verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='main_app.Survey', verbose_name='опрос'),
        ),
        migrations.AlterField(
            model_name='optionanswer',
            name='number_answer',
            field=models.IntegerField(verbose_name='номер ответа'),
        ),
    ]
