# Generated by Django 2.2.10 on 2022-01-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20220112_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionanswer',
            name='number_answer',
        ),
    ]
