# Generated by Django 2.2.10 on 2022-01-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_optionanswer_number_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnonymous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='session_key')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='main_app.UserAnonymous', verbose_name='id user'),
        ),
    ]
