# Generated by Django 2.2.10 on 2022-01-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20220113_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranonymous',
            name='key',
            field=models.CharField(max_length=128, unique=True, verbose_name='session_key'),
        ),
    ]
