# Generated by Django 4.0.1 on 2022-01-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20220113_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option_answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='option_answer_text',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='main_app.optionanswer', verbose_name='опциональный ответ'),
            preserve_default=False,
        ),
    ]
