# Generated by Django 4.0.1 on 2022-01-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_answer_option_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranonymous',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
