# Generated by Django 4.0.1 on 2022-01-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_useranonymous_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranonymous',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
