# Generated by Django 4.0.1 on 2022-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_useranonymous_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=256, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option_answer_text',
            field=models.ManyToManyField(blank=True, related_name='answer', to='main_app.OptionAnswer', verbose_name='опциональный ответ'),
        ),
    ]
