# Generated by Django 4.0.1 on 2022-01-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option_answer_text',
            field=models.ManyToManyField(related_name='answer', to='main_app.OptionAnswer', verbose_name='опциональный ответ'),
        ),
    ]
