# Generated by Django 4.0.1 on 2022-01-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_answer_option_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option_answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='option_answer_text',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='main_app.optionanswer', verbose_name='опциональный ответ'),
            preserve_default=False,
        ),
    ]
