# Generated by Django 4.0.1 on 2022-01-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_answer_option_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='answer_text_id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='option_answer_text',
            new_name='option_answer_text_id',
        ),
    ]
