# Generated by Django 4.0.1 on 2022-01-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_rename_answer_text_answer_answer_text_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionanswer',
            old_name='option_answer_text',
            new_name='option_answer_text_id',
        ),
    ]
