# Generated by Django 4.0.1 on 2022-01-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_rename_option_answer_text_optionanswer_option_answer_text_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text_id',
            new_name='answer_text',
        ),
    ]
