# Generated by Django 4.0.1 on 2022-01-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_rename_answer_text_id_answer_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionanswer',
            old_name='option_answer_text_id',
            new_name='option_answer_text',
        ),
    ]
