# Generated by Django 4.0.1 on 2022-01-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_rename_option_answer_text_id_optionanswer_option_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option_answer_text_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='option_answer_text_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='answer', to='main_app.OptionAnswer', verbose_name='опциональный ответ'),
        ),
    ]
